Repository puppetlabs/ruby-pwsh, pull requests merged in 2020-11, with the labels that each got.

#56 (GH-55) Handle intentionally empty arrays
  appveyor.yml
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  lib/pwsh.rb
  lib/pwsh/util.rb
  spec/unit/pwsh_spec.rb
Labels: bugfix

#58 (GH-57) Handle datetimes in dsc
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1
Labels: bugfix

#60 (GH-59) Refactor away from Simple Provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: enhancement

#61 (GH-74) Remove special handling for ensure in the dsc base provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  lib/pwsh.rb
Labels: enhancement

#62 (GH-81) Handle parameters in the dsc base provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: enhancement

#65 (MAINT) Prep for 0.6.0 release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint

#68 (Maint) merge back 0.6.0 Release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint

#66 (maint) Minor README change
  README.md
Labels: maint

#70 (maint) - Removal of inappropriate terminology
  CONTRIBUTING.md
  README.md
  metadata.json
Labels: bugfix

#71 (MAINT) Prep for 0.6.1 release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint

#72 (maint) Release mergeback v0.6.1
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint
