Repository puppetlabs/ruby-pwsh, pull requests merged in 2021-03, with the labels that each got.

#113 (MAINT) Clarify supported platforms
  README.md
  metadata.json
Labels: enhancement

#115 (Maint) Mergeback 0.8.0 Release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint

#118 (Maint) Ensure canonicalize correctly compares sorted hashes
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: bugfix
