Repository puppetlabs/ruby-pwsh, pull requests merged in 2021-06, with the labels that each got.

#150 (GH-145) Improve DSC secrets redaction
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: enhancement

#151 (GH-144) Enable order-insensitive comparisons for DSC
  .travis.yml
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix

#153 (GH-141) Simplify set logic in DSC Base Provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: maint

#156 (MAINT) Refactor secrets handling in DSC
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: maint

#157 (GH-154) Fix canonicalization in `get` method for DSC Base Provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix

#158 (GH-155) Fix CIM Instance munging in `invoke_get_method` for DSC Base Provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix

#159 (GH-154) Fix return data from `Invoke-DscResource` for empty strings and single item arrays in DSC Base Provider
  lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1
Labels: bugfix

#160 (GH-154) Ensure values returned from `invoke_get_method` are recursively sorted in the DSC Base Provider to reduce canonicalization warnings.
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix

#152 (GH-147) Refactor Invocation methods to use shared helper and write error logs when appropriate
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: enhancement

#161 (GH-67) Move CI to Github Actions
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
Labels: maint

#168 (GH-142) Refactor invoke_get_method to reduce complex/fragile code paths
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: maint

#167 (MAINT) Ensure DSC does not write accidental errors
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: maint

#166 (GH-163) Add basic DSC acceptance tests
  .github/workflows/ci.yml
  .gitignore
  Gemfile
  Rakefile
  spec/acceptance/dsc/basic.rb
Labels: maint

#169 (IAC-1657) Fix for invalid DateTime value error in `invoke_get_method`
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix

#124 (GH-145) Add insync? and invoke_test_method to dsc provider
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: enhancement

#170 (MAINT) Prep for 0.9.0 release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint

#171 Mergeback 0.9.0 Release
  CHANGELOG.md
  lib/pwsh/version.rb
  metadata.json
Labels: maint
