Repository puppetlabs/ruby-pwsh, pull requests merged in 2024-02, with the labels that each got.

#285 (maint) - Update mend trigger
  .github/workflows/mend.yml
Labels: maintenance

#287 (test) - update workflow ref to test changes
  .github/workflows/mend.yml
Labels: maintenance

#288 Revert "(test) - update trigger to test changes"
  .github/workflows/mend.yml
Labels: maintenance

#291 Fix enum idempotency
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: bugfix, community

#289 (maint) - refactor retry_invoke_dsc_resource
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: maintenance

#295 (CAT-1724) - Fix Provider returned data not matching Type Schema
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: bugfix
