Repository puppetlabs/ruby-pwsh, pull requests merged in 2024-01, with the labels that each got.

#274 pdksync - "(CAT-1618) - Add code coverage to ci"
  .github/workflows/ci.yml
  Gemfile
  Rakefile
  spec/spec_helper.rb
Labels: maintenance

#276 pdksync - "(CAT-1618) - run code coverage on main"
  .github/workflows/ci.yml
Labels: maintenance

#279 (CAT-1688) Upgrade rubocop to `~> 1.50.0`
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
Labels: bugfix

#280 pdksync - (CAT-1618) - Remove deprecated/obsolete codecov gem
  Gemfile
  spec/spec_helper.rb
Labels: maintenance

#283 (maint) - Run all unit test files during rake spec
  Rakefile
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: maintenance

#282 (feat) - add retries on failed dsc invocation
  .rubocop_todo.yml
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
Labels: feature
