Repository puppetlabs/ruby-pwsh, pull requests merged in 2024-09, with the labels that each got.

#338 AlmaLinux 8/9 added to metadata.json
  metadata.json
Labels: enhancement

#342 Revert "Fix empty string nullification"
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
  lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1
Labels: bugfix

#341 updated readme for almalinux
  README.md
Labels: maintenance

#346 (CAT-2061) Fix empty string nullification
  lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Labels: bugfix
